"use client";

import { useSearchParams } from "next/navigation";
import { useEffect, useState, Suspense } from "react";
import {
  CircularProgress,
  Typography,
  Stack,
  Divider,
  Chip,
} from "@mui/material";
import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded";
import ErrorRoundedIcon from "@mui/icons-material/ErrorRounded";
import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";
import axiosInstance from "@/helper/Axios";

function VerifyContent() {
  const searchParams = useSearchParams();
  const docId = searchParams.get("id");
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!docId) {
      setError("No document ID provided.");
      setLoading(false);
      return;
    }

    axiosInstance
      .post("/document/getFileDetail", { fileId: docId })
      .then((res) => {
        setData(res.body);
        setLoading(false);
      })
      .catch(() => {
        setError("Document not found or verification failed.");
        setLoading(false);
      });
  }, [docId]);

  if (loading) {
    return (
      <div style={{ backgroundColor: "#f9fafb", minHeight: "100vh" }} className="flex items-center justify-center">
        <CircularProgress />
      </div>
    );
  }

  if (error || !data) {
    return (
      <div style={{ backgroundColor: "#f9fafb", minHeight: "100vh" }} className="flex flex-col items-center justify-center gap-4 p-8">
        <ErrorRoundedIcon sx={{ fontSize: 64, color: "#ef4444" }} />
        <Typography variant="h5" fontWeight="bold" color="error">
          Verification Failed
        </Typography>
        <Typography sx={{ color: "#6b7280" }}>{error}</Typography>
      </div>
    );
  }

  const reportData = data.report ? JSON.parse(data.report) : null;

  return (
    <div style={{ backgroundColor: "#f9fafb", minHeight: "100vh" }}>
      <div style={{ maxWidth: "768px", margin: "0 auto", padding: "40px 24px" }}>

        {/* Header bar */}
        <div style={{ backgroundColor: "#1d4ed8", borderRadius: "12px", padding: "16px 20px", marginBottom: "24px", display: "flex", alignItems: "center", gap: "12px" }}>
          <img src="/dict_logo.png" alt="DICT" style={{ width: 40, height: 40 }} />
          <div>
            <Typography sx={{ fontWeight: 700, color: "#ffffff", fontSize: "16px" }}>
              DocVal — Document Evaluation System
            </Typography>
            <Typography sx={{ color: "#bfdbfe", fontSize: "12px" }}>
              Department of Information and Communications Technology
            </Typography>
          </div>
        </div>

        {/* Verified Banner */}
        <div style={{ backgroundColor: "#f0fdf4", border: "1px solid #bbf7d0", borderRadius: "12px", padding: "16px 20px", marginBottom: "24px", display: "flex", alignItems: "center", gap: "12px" }}>
          <CheckCircleRoundedIcon sx={{ color: "#16a34a", fontSize: 40 }} />
          <div>
            <Typography sx={{ fontWeight: 700, color: "#15803d", fontSize: "18px" }}>
              Document Verified ✓
            </Typography>
            <Typography sx={{ color: "#166534", fontSize: "13px" }}>
              This report was officially generated by DocVal — the Document Evaluation System of DICT.
            </Typography>
          </div>
        </div>

        {/* Document Info Card */}
        <div style={{ backgroundColor: "#ffffff", border: "1px solid #e5e7eb", borderRadius: "12px", padding: "20px", marginBottom: "24px" }}>
          <Typography sx={{ fontWeight: 700, color: "#111827", fontSize: "18px", marginBottom: "8px" }}>
            {data.title}
          </Typography>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", marginBottom: "12px" }}>
            <Chip label={data.doc_type} size="small" color="primary" />
            <Chip label={data.doc_class} size="small" />
            <Chip label={data.status} size="small" color="success" />
          </div>
          <Typography sx={{ color: "#374151", fontSize: "13px", marginBottom: "4px" }}>
            Sender: <strong>{data.sender_office}</strong>
          </Typography>
          <Typography sx={{ color: "#374151", fontSize: "13px" }}>
            Date Received:{" "}
            <strong>
              {data.date_created
                ? new Date(data.date_created).toISOString().split("T")[0]
                : "—"}
            </strong>
          </Typography>
        </div>

        {/* Report Content Card */}
        {reportData ? (
          <div style={{ backgroundColor: "#ffffff", border: "1px solid #e5e7eb", borderRadius: "12px", padding: "20px" }}>
            <Typography sx={{ color: "#6b7280", fontSize: "11px", fontStyle: "italic", marginBottom: "16px" }}>
              Report powered by Gemini AI <AutoAwesomeRoundedIcon sx={{ fontSize: 10 }} />
            </Typography>

            <Stack spacing={3}>
              {[
                { key: "summary", title: "Summary", type: "text" },
                { key: "key_points", title: "Key Points", type: "list" },
                { key: "scope_of_work", title: "Scope of Work", type: "text" },
                { key: "deliverables", title: "Deliverables", type: "list" },
                { key: "timeline", title: "Timeline", type: "text" },
                { key: "budget_summary", title: "Budget Summary", type: "text" },
                { key: "recommendations", title: "Recommendations", type: "list" },
                { key: "references", title: "References", type: "list" },
              ].map(({ key, title, type }) => {
                const content = reportData[key];
                if (!content) return null;
                if (Array.isArray(content) && content.length === 0) return null;
                if (typeof content === "string" && !content.trim()) return null;

                return (
                  <div key={key}>
                    <Typography sx={{ fontWeight: 700, color: "#111827", fontSize: "14px", marginBottom: "6px" }}>
                      {title}
                    </Typography>
                    {type === "text" ? (
                      <Typography sx={{ color: "#374151", fontSize: "13px", textAlign: "justify", lineHeight: 1.6 }}>
                        {content}
                      </Typography>
                    ) : (
                      <Stack spacing={0.5}>
                        {content.map((item, i) => (
                          <Typography key={i} sx={{ color: "#374151", fontSize: "13px", lineHeight: 1.6 }}>
                            • {item}
                          </Typography>
                        ))}
                      </Stack>
                    )}
                    <Divider sx={{ mt: 2 }} />
                  </div>
                );
              })}
            </Stack>
          </div>
        ) : (
          <Typography sx={{ color: "#6b7280", fontStyle: "italic" }}>
            No report content available.
          </Typography>
        )}

        {/* Footer */}
        <div style={{ textAlign: "center", marginTop: "32px" }}>
          <Typography sx={{ color: "#9ca3af", fontSize: "11px" }}>
            Verified via DocVal — DICT Document Evaluation System
          </Typography>
        </div>

      </div>
    </div>
  );
}

export default function VerifyPage() {
  return (
    <Suspense
      fallback={
        <div style={{ backgroundColor: "#f9fafb", minHeight: "100vh" }} className="flex items-center justify-center">
          <CircularProgress />
        </div>
      }
    >
      <VerifyContent />
    </Suspense>
  );
}